name: GitHub Actions Demo

on:
  push:
    branches: 
      - main
    paths-ignore: 
      - .github/**
  pull_request:
    branches: 
      - main
  schedule:
    - cron: "15 6 * * 0"
  workflow_dispatch:

jobs:
  job:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - run: echo ${{ github.event_name }}
      - uses: actions/checkout@v3.3.0
      - run: echo $(git rev-parse --abbrev-ref HEAD)
      - run: echo $(ls)
  
