name: Reuse other workflow

on:
  workflow_dispatch:

jobs:
  call-workflow:
    uses: ./.github/workflows/reusable.yml
    with:
      who-to-greet: "Calvin"
  use-output:
    needs: call-workflow
    runs-on: ubuntu-latest
    steps:
      - run: echo ${{ needs.call-workflow.outputs.current-time }}
